# Generated by Django 3.2.12 on 2022-12-27 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('longitude', models.CharField(max_length=128)),
                ('latitude', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=8)),
                ('available_on', models.TimeField()),
                ('available_off', models.TimeField()),
                ('day_off', models.CharField(max_length=128)),
                ('warm_toilet_seat', models.BooleanField()),
                ('seat_cleaner', models.BooleanField()),
                ('luggage_storage', models.BooleanField()),
                ('ostomate', models.BooleanField()),
                ('barrier', models.BooleanField()),
                ('crib', models.BooleanField()),
                ('parking', models.BooleanField()),
                ('by_gender', models.BooleanField()),
                ('powder_room', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('star', models.IntegerField()),
                ('is_name', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toiletapp.locations')),
            ],
        ),
    ]
