# Generated by Django 3.2.12 on 2022-12-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toiletapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='name2',
            field=models.CharField(default='nametest', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locations',
            name='day_off',
            field=models.BooleanField(),
        ),
    ]
