# Generated by Django 3.2.12 on 2022-12-27 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toiletapp', '0002_auto_20221227_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='name2',
        ),
    ]
