# Generated by Django 3.2.12 on 2022-12-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toiletapp', '0003_remove_locations_name2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='latitude',
            field=models.FloatField(max_length=128),
        ),
        migrations.AlterField(
            model_name='locations',
            name='longitude',
            field=models.FloatField(max_length=128),
        ),
    ]
