# Generated by Django 3.2.12 on 2022-12-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toiletapp', '0004_auto_20221227_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='day_off',
        ),
        migrations.AddField(
            model_name='locations',
            name='kind',
            field=models.CharField(default='test', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locations',
            name='remarks',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locations',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='locations',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
