# Generated by Django 3.2.12 on 2022-12-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toiletapp', '0005_auto_20221227_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='remarks',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
