# Generated by Django 3.2.12 on 2023-01-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toiletapp', '0006_alter_locations_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='accepted',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
