# Generated by Django 3.2.12 on 2023-01-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toiletapp', '0007_locations_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='reports',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
